import type { Trip, Organizer, User, Booking, City, Dispute, Payout, PromoCode, HomeBanner, AdminNotification, AuditLog, TripChangeLog, AdminUser, Category, Interest } from './types';
import { ShieldCheck, ListChecks, Banknote, UserRound, AlertTriangle, Mountain, Heart, Camera, Utensils, Sailboat, Activity } from 'lucide-react';

export const cities: City[] = [
    { id: 'Goa', name: 'Goa', enabled: true },
    { id: 'Varanasi', name: 'Varanasi', enabled: true },
    { id: 'Rishikesh', name: 'Rishikesh', enabled: true },
    { id: 'Delhi', name: 'Delhi', enabled: true },
    { id: 'Munnar', name: 'Munnar', enabled: true },
    { id: 'Manali', name: 'Manali', enabled: true },
    { id: 'Jaipur', name: 'Jaipur', enabled: false },
    { id: 'Hampi', name: 'Hampi', enabled: true },
    { id: 'Andaman', name: 'Andaman', enabled: true },
];

// DEV_COMMENT: Centrally managed categories and interests for trips.
export const categories: Category[] = [
  { id: 'cat1', name: 'Adventure', icon: Mountain, status: 'Active' },
  { id: 'cat2', name: 'Cultural', icon: Camera, status: 'Active' },
  { id: 'cat3', name: 'Relaxation', icon: Sailboat, status: 'Active' },
  { id: 'cat4', name: 'Spiritual', icon: Heart, status: 'Active' },
  { id: 'cat5', name: 'Culinary', icon: Utensils, status: 'Inactive' },
  { id: 'cat6', name: 'City Tour', icon: Activity, status: 'Active' },
];

export const interests: Interest[] = [
  { id: 'int1', name: 'Hiking', status: 'Active' },
  { id: 'int2', name: 'Beaches', status: 'Active' },
  { id: 'int3', name: 'Photography', status: 'Active' },
  { id: 'int4', name: 'Foodie', status: 'Active' },
  { id: 'int5', name: 'History', status: 'Active' },
  { id: 'int6', name: 'Nightlife', status: 'Active' },
  { id: 'int7', name: 'Yoga', status: 'Inactive' },
  { id: 'int8', name: 'Mountains', status: 'Active' },
];

export const organizers: Organizer[] = [
    {
        id: 'VND001',
        name: 'Himalayan Adventures',
        email: 'contact@himalayanadventures.com',
        joinDate: '2023-09-15',
        organizerType: 'Private Limited',
        logo: 'https://placehold.co/128x128.png',
        phone: '+919988776655',
        address: '123, Adventure Lane, Manali, Himachal Pradesh',
        website: 'https://himalayanadventures.com',
        experience: 10,
        specializations: ['Trekking', 'Adventure', 'Himalayas'],
        isProfileComplete: true,
        authorizedSignatoryName: 'Aarav Sharma',
        authorizedSignatoryId: 'ASDFG1234H',
        emergencyContact: '+919876543210',
        pan: 'ABCDE1234F',
        gstin: '29ABCDE1234F1Z5',
        bankAccountNumber: '123456789012',
        ifscCode: 'HDFC0001234',
        kycStatus: 'Verified',
        vendorAgreementStatus: 'Verified',
        documents: [
            { docType: 'id_proof', docTitle: "Identity Document (PAN/Aadhar)", status: 'Verified', fileUrl: '#' },
            { docType: 'address_proof', docTitle: "Address Proof", status: 'Verified', fileUrl: '#' },
            { docType: 'business_registration', docTitle: "Business Registration Proof", status: 'Verified', fileUrl: '#' },
        ]
    },
    {
        id: 'VND002',
        name: 'Incredible India Tours',
        email: 'hello@incredibleindiatours.co',
        joinDate: '2023-10-02',
        phone: '+919988776656',
        isProfileComplete: true,
        kycStatus: 'Verified',
        vendorAgreementStatus: 'Verified',
        documents: [],
        pan: 'FGHIJ5678K',
    },
    {
        id: 'VND003',
        name: 'Bharat Explorers',
        email: 'support@bharatexplorers.com',
        joinDate: '2024-01-20',
        isProfileComplete: false,
        kycStatus: 'Incomplete',
        vendorAgreementStatus: 'Not Submitted',
        documents: [
            { docType: 'id_proof', docTitle: "Identity Document (PAN/Aadhar)", status: 'Pending' },
            { docType: 'address_proof', docTitle: "Address Proof", status: 'Pending' },
            { docType: 'business_registration', docTitle: "Business Registration Proof", status: 'Pending' },
        ]
    },
    {
        id: 'VND004',
        name: 'Coastal Escapes',
        email: 'info@coastalescapes.net',
        joinDate: '2024-03-11',
        isProfileComplete: true,
        kycStatus: 'Rejected',
        vendorAgreementStatus: 'Submitted',
        documents: [
            { docType: 'id_proof', docTitle: "Identity Document (PAN/Aadhar)", status: 'Verified', fileUrl: '#' },
            { docType: 'address_proof', docTitle: "Address Proof", status: 'Rejected', rejectionReason: 'Document is not legible. Please re-upload.', fileUrl: '#' },
            { docType: 'business_registration', docTitle: "Business Registration Proof", status: 'Pending' },
        ],
        pan: 'KLMNO9101L',
    },
    {
        id: 'VND005',
        name: 'Jungle Journeys',
        email: 'contact@jungle.com',
        joinDate: '2024-05-22',
        isProfileComplete: true,
        kycStatus: 'Pending',
        vendorAgreementStatus: 'Submitted',
        documents: [
            { docType: 'id_proof', docTitle: "Identity Document (PAN/Aadhar)", status: 'Uploaded', fileUrl: '#' },
            { docType: 'address_proof', docTitle: "Address Proof", status: 'Uploaded', fileUrl: '#' },
            { docType: 'business_registration', docTitle: "Business Registration Proof", status: 'Uploaded', fileUrl: '#' },
        ],
        pan: 'PQRST1121M',
    },
    {
        id: 'VND006',
        name: 'New Self-Registered Organizer',
        email: 'new-organizer@example.com',
        phone: '+919513626262',
        joinDate: '2024-07-28',
        isProfileComplete: false,
        kycStatus: 'Incomplete',
        vendorAgreementStatus: 'Not Submitted',
        documents: [
            { docType: 'id_proof', docTitle: "Identity Document (PAN/Aadhar)", status: 'Pending' },
            { docType: 'address_proof', docTitle: "Address Proof", status: 'Pending' },
            { docType: 'business_registration', docTitle: "Business Registration Proof", status: 'Pending' },
        ]
    }
];

export const users: User[] = [
    {
        id: 'USR001',
        name: 'Rohan Sharma',
        email: 'rohan@example.com',
        phone: '+919876543210',
        joinDate: '2023-10-21',
        status: 'Active',
        isProfileComplete: true,
        walletBalance: 4000,
        referralCode: 'ROHAN4000',
        referredBy: null,
        avatar: 'https://placehold.co/128x128.png',
        gender: 'Male',
        dateOfBirth: '1995-08-15',
        bloodGroup: 'O+',
        emergencyContact: '+919876543211',
        address: {
            street: '123, Main Street',
            city: 'Mumbai',
            pincode: '400001'
        },
        interests: ['Adventure', 'Hiking', 'Photography'],
        travelPreferences: 'Mid-range',
        marketingOptIn: true,
        walletTransactions: [
            { id: 'txn1', date: '2024-07-20T10:00:00Z', description: 'Referral Bonus from Priya Patel', amount: 1500, type: 'Credit', source: 'Referral' },
            { id: 'txn2', date: '2024-07-10T12:30:00Z', description: 'Used for Booking BK123', amount: -2500, type: 'Debit', source: 'Booking' },
            { id: 'txn3', date: '2024-06-15T09:00:00Z', description: 'Refund for cancelled trip', amount: 5000, type: 'Credit', source: 'Refund' },
            { id: 'txn5', date: '2024-08-01T11:00:00Z', description: 'Admin Credit: Goodwill gesture for service issue.', amount: 1000, type: 'Credit', source: 'Admin Adjustment' },
        ]
    },
    {
        id: 'USR002',
        name: 'Priya Patel',
        email: 'priya@example.com',
        phone: '+919876543211',
        joinDate: '2023-11-05',
        status: 'Active',
        isProfileComplete: false, // Incomplete profile example
        walletBalance: 2000,
        referralCode: 'PRIYA2000',
        referredBy: 'USR001',
        avatar: 'https://placehold.co/128x128.png',
        gender: 'Female',
        dateOfBirth: '1998-05-20',
        bloodGroup: 'A+',
        address: {
            street: '456, Park Avenue',
            city: 'Ahmedabad',
            pincode: '380009'
        },
        marketingOptIn: true,
        walletTransactions: [
             { id: 'txn4', date: '2024-07-20T10:00:00Z', description: 'Signup Bonus', amount: 1000, type: 'Credit', source: 'Referral' },
        ]
    },
    {
        id: 'USR003',
        name: 'Arjun Singh',
        email: 'arjun@example.com',
        phone: '+919876543212',
        joinDate: '2023-11-12',
        status: 'Suspended',
        isProfileComplete: true,
        walletBalance: 0,
        referralCode: 'ARJUN0',
        referredBy: null,
        avatar: 'https://placehold.co/128x128.png',
        bloodGroup: 'B-',
    },
    {
        id: 'USR004',
        name: 'Ananya Gupta',
        email: 'ananya@example.com',
        phone: '+919876543213',
        joinDate: '2023-12-01',
        status: 'Active',
        isProfileComplete: true,
        walletBalance: 8000,
        referralCode: 'ANANYA8000',
        referredBy: 'USR002',
        avatar: 'https://placehold.co/128x128.png'
    },
];

const defaultCancellationPolicy = 'Full refund for cancellations made at least 30 days before the trip. 50% refund for cancellations made between 15 and 30 days before. No refund for cancellations made within 15 days of the trip.';
const defaultCancellationRules = [
    { days: 30, refundPercentage: 100 },
    { days: 15, refundPercentage: 50 },
    { days: 0, refundPercentage: 0 },
];

const mockTripChangeLogs: TripChangeLog[] = [
    { id: 'log_trip3_1', timestamp: '2024-07-25T14:30:00Z', changedBy: 'Himalayan Adventures', section: 'Batch', changeType: 'Edited', remarks: 'Increased price due to high season demand.', changedFields: 'Batch "Diwali Special" Price: ₹200,000 → ₹220,000' },
    { id: 'log_trip3_2', timestamp: '2024-07-24T10:00:00Z', changedBy: 'Himalayan Adventures', section: 'Trip', changeType: 'Edited', remarks: 'Added more details to the description for clarity.', changedFields: 'Description updated.' },
    { id: 'log_trip3_3', timestamp: '2024-07-23T09:00:00Z', changedBy: 'Admin', section: 'Trip', changeType: 'Status Change', remarks: 'Approved trip for listing.', changedFields: 'Status: Pending Approval → Published' },
];

export const trips: Trip[] = [
    {
        id: '1',
        slug: 'romantic-getaway-in-goa',
        title: 'Romantic Getaway in Goa',
        location: 'Goa, India',
        city: 'Goa',
        tripType: 'Relaxation',
        interests: ['Beaches', 'Nightlife'],
        difficulty: 'Easy',
        duration: '3 Days, 2 Nights',
        minAge: 18,
        maxAge: 65,
        pickupCity: 'Goa',
        pickupPoints: [
            { label: 'Goa Airport (GOI)', time: '10:00 AM', mapsLink: 'https://maps.google.com' },
            { label: 'Madgaon Railway Station', time: '11:30 AM', mapsLink: 'https://maps.google.com' },
        ],
        dropoffPoints: [
            { label: 'Goa Airport (GOI)', time: '05:00 PM', mapsLink: 'https://maps.google.com' },
        ],
        category: 'Romantic',
        isFeaturedRequest: true,
        price: 96000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'goa beach sunset',
        gallery: [
            { url: 'https://placehold.co/600x400.png', hint: 'resort pool' },
            { url: 'https://placehold.co/600x400.png', hint: 'couple dinner beach' },
             { url: 'https://placehold.co/600x400.png', hint: 'beach shack' },
            { url: 'https://placehold.co/600x400.png', hint: 'goa church' },
            { url: 'https://placehold.co/600x400.png', hint: 'dolphin spotting' },
        ],
        description: 'Experience the magic of Goa, from serene beaches to vibrant nightlife.',
        inclusions: ['Hotel accommodation', 'Welcome dinner', 'Scooter rental for a day'],
        exclusions: ['Airfare', 'Personal expenses', 'Water sports'],
        itinerary: [
            { day: 1, title: 'Arrival in Goa', description: 'Check into your resort and enjoy a welcome dinner by the beach.' },
            { day: 2, title: 'North Goa Exploration', description: 'Visit Calangute and Baga beaches, and explore the Anjuna flea market.' },
        ],
        batches: [
            { id: 'batch-1-1', startDate: '2024-10-10', endDate: '2024-10-12', availableSlots: 5, maxParticipants: 10, status: 'Active', notes: "Diwali Special" },
            { id: 'batch-1-2', startDate: '2024-11-15', endDate: '2024-11-17', availableSlots: 8, maxParticipants: 10, status: 'Active' },
        ],
        reviews: [
            { id: 'rev-1', userId: 'USR002', rating: 5, comment: 'Absolutely magical experience!' }
        ],
        faqs: [
            { question: 'What is the best time to visit?', answer: 'The best time to visit Goa is from November to February when the weather is pleasant.' },
            { question: 'Is airfare included?', answer: 'No, airfare is not included in the trip price. You will need to book your own flights to and from Goa.'}
        ],
        organizerId: 'VND002',
        isFeatured: true,
        isBannerTrip: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '2',
        slug: 'varanasi-spiritual-trails',
        title: 'Varanasi\'s Spiritual Trails',
        location: 'Varanasi, India',
        city: 'Varanasi',
        tripType: 'Spiritual',
        interests: ['History', 'Culture'],
        difficulty: 'Easy',
        duration: '4 Days, 3 Nights',
        minAge: 16,
        maxAge: 70,
        pickupCity: 'Varanasi',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Cultural',
        isFeaturedRequest: false,
        price: 120000,
        taxIncluded: false,
        taxPercentage: 5,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'varanasi ganges ghats',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'ganges boat ride' },
            { url: 'https://placehold.co/600x400.png', hint: 'sadhu religious' },
             { url: 'https://placehold.co/600x400.png', hint: 'temple architecture' },
            { url: 'https://placehold.co/600x400.png', hint: 'evening aarti ceremony' },
            { url: 'https://placehold.co/600x400.png', hint: 'market street' },
        ],
        description: 'Discover the serene beauty of Varanasi\'s ghats and ancient temples.',
        inclusions: ['Temple entry fees', 'Ganga aarti boat ride', 'Local guide'],
        exclusions: ['Flights', 'Meals'],
        itinerary: [],
        batches: [
            { id: 'batch-2-1', startDate: '2024-11-01', endDate: '2024-11-04', availableSlots: 10, maxParticipants: 15, status: 'Active' },
        ],
        reviews: [],
        faqs: [],
        organizerId: 'VND002',
        isFeatured: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '3',
        slug: 'rishikesh-adventure-rush',
        title: 'Rishikesh Adventure Rush',
        location: 'Rishikesh, India',
        city: 'Rishikesh',
        tripType: 'Adventure',
        interests: ['Hiking', 'Mountains'],
        difficulty: 'Moderate',
        duration: '5 Days, 4 Nights',
        minAge: 18,
        maxAge: 45,
        pickupCity: 'Delhi',
        pickupPoints: [
            { label: 'Kashmiri Gate ISBT', time: '09:00 PM', mapsLink: 'https://maps.google.com' },
            { label: 'Majnu-ka-tilla', time: '10:00 PM', mapsLink: 'https://maps.google.com' },
        ],
        dropoffPoints: [
            { label: 'Rishikesh Bus Stand', time: '07:00 AM', mapsLink: 'https://maps.google.com' },
        ],
        category: 'Adventure',
        isFeaturedRequest: true,
        price: 200000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'rishikesh river rafting',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'bungee jumping' },
            { url: 'https://placehold.co/600x400.png', hint: 'camping tents night' },
             { url: 'https://placehold.co/600x400.png', hint: 'ganga river' },
            { url: 'https://placehold.co/600x400.png', hint: 'mountain view' },
            { url: 'https://placehold.co/600x400.png', hint: 'group bonfire' },
        ],
        description: 'An adrenaline-fueled journey through the stunning landscapes of Rishikesh.',
        inclusions: ['River rafting', 'Guided hikes', 'Bungee jumping'],
        exclusions: ['International airfare', 'Visa fees'],
        itinerary: [],
        batches: [
            { id: 'batch-3-1', startDate: '2024-09-15', endDate: '2024-09-19', availableSlots: 12, maxParticipants: 20, status: 'Active', priceOverride: 220000, notes: "High season pricing." },
        ],
        reviews: [],
        faqs: [],
        organizerId: 'VND001',
        isFeatured: true,
        isBannerTrip: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
        changeLogs: mockTripChangeLogs,
    },
    {
        id: '4',
        slug: 'historical-delhi-exploration',
        title: 'Historical Delhi Exploration',
        location: 'Delhi, India',
        city: 'Delhi',
        tripType: 'City Tour',
        interests: ['History', 'Foodie'],
        difficulty: 'Easy',
        duration: '2 Days, 1 Night',
        minAge: 10,
        maxAge: 80,
        pickupCity: 'Delhi',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Historical',
        isFeaturedRequest: false,
        price: 108000,
        taxIncluded: false,
        taxPercentage: 5,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'delhi india gate',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'qutub minar' },
            { url: 'https://placehold.co/600x400.png', hint: 'humayun tomb' },
             { url: 'https://placehold.co/600x400.png', hint: 'lotus temple' },
            { url: 'https://placehold.co/600x400.png', hint: 'red fort' },
            { url: 'https://placehold.co/600x400.png', hint: 'old delhi market' },
        ],
        description: 'Walk through history in the bustling capital city of Delhi.',
        inclusions: ['Qutub Minar tickets', 'Old Delhi food tour', 'Local transport pass'],
        exclusions: ['Lunches and dinners', 'Entry fees to other monuments'],
        itinerary: [],
        batches: [],
        reviews: [],
        faqs: [],
        organizerId: 'VND003',
        isFeatured: true,
        isBannerTrip: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '5',
        slug: 'munnar-tea-gardens-escape',
        title: 'Munnar Tea Gardens Escape',
        location: 'Munnar, Kerala',
        city: 'Munnar',
        tripType: 'Relaxation',
        interests: ['Beaches', 'Photography'],
        difficulty: 'Easy',
        duration: '4 Days, 3 Nights',
        minAge: 12,
        maxAge: 65,
        pickupCity: 'Munnar',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Nature',
        isFeaturedRequest: true,
        price: 144000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'munnar tea plantation',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'kerala backwaters' },
            { url: 'https://placehold.co/600x400.png', hint: 'waterfall nature' },
             { url: 'https://placehold.co/600x400.png', hint: 'spice garden' },
            { url: 'https://placehold.co/600x400.png', hint: 'elephant ride' },
            { url: 'https://placehold.co/600x400.png', hint: 'resort view' },
        ],
        description: 'Explore the rich biodiversity and sprawling tea gardens of Munnar.',
        inclusions: ['Guided nature hikes', 'Tea factory visit', 'National park fees'],
        exclusions: ['Meals', 'Optional activities'],
        itinerary: [],
        batches: [],
        reviews: [],
        faqs: [],
        organizerId: 'VND001',
        isFeatured: true,
        isBannerTrip: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '6',
        slug: 'majestic-manali-himalayas',
        title: 'Majestic Manali & Himalayas',
        location: 'Manali, Himachal Pradesh',
        city: 'Manali',
        tripType: 'Adventure',
        interests: ['Hiking', 'Mountains'],
        difficulty: 'Challenging',
        duration: '7 Days, 6 Nights',
        minAge: 18,
        maxAge: 50,
        pickupCity: 'Manali',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Adventure',
        isFeaturedRequest: false,
        price: 176000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'manali mountains snow',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'solang valley' },
            { url: 'https://placehold.co/600x400.png', hint: 'rohtang pass' },
             { url: 'https://placehold.co/600x400.png', hint: 'trekking group' },
            { url: 'https://placehold.co/600x400.png', hint: 'hidimba temple' },
            { url: 'https://placehold.co/600x400.png', hint: 'old manali' },
        ],
        description: 'Find peace and breathtaking views in the majestic Himalayas near Manali.',
        inclusions: ['Mountain cabin stay', 'Scenic drives', 'Bonfire dinner'],
        exclusions: ['Ski passes', 'Equipment rental'],
        itinerary: [],
        batches: [],
        reviews: [],
        faqs: [],
        organizerId: 'VND001',
        isFeatured: true,
        status: 'Published',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
     {
        id: '7',
        slug: 'royal-rajasthan-jaipur',
        title: 'Royal Rajasthan in Jaipur',
        location: 'Jaipur, Rajasthan',
        city: 'Jaipur',
        tripType: 'Cultural',
        interests: ['History', 'Photography'],
        difficulty: 'Easy',
        duration: '3 Days, 2 Nights',
        minAge: 5,
        maxAge: 85,
        pickupCity: 'Jaipur',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Cultural',
        isFeaturedRequest: false,
        price: 144000,
        taxIncluded: false,
        taxPercentage: 5,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'jaipur hawa mahal',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'amer fort' },
            { url: 'https://placehold.co/600x400.png', hint: 'city palace' },
             { url: 'https://placehold.co/600x400.png', hint: 'jantar mantar' },
            { url: 'https://placehold.co/600x400.png', hint: 'rajasthani thali' },
            { url: 'https://placehold.co/600x400.png', hint: 'local market' },
        ],
        description: 'Experience the iconic pink city and royal heritage of Jaipur.',
        inclusions: [],
        exclusions: [],
        itinerary: [],
        batches: [],
        reviews: [],
        faqs: [],
        organizerId: 'VND001',
        isFeatured: false,
        status: 'Unlisted',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '8',
        slug: 'hampi-ancient-ruins',
        title: 'Hampi\'s Ancient Ruins',
        location: 'Hampi, Karnataka',
        city: 'Hampi',
        tripType: 'Cultural',
        interests: ['History', 'Photography'],
        difficulty: 'Moderate',
        duration: '3 Days, 2 Nights',
        minAge: 12,
        maxAge: 60,
        pickupCity: 'Hampi',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Historical',
        isFeaturedRequest: false,
        price: 76000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'hampi stone chariot',
        gallery: [
             { url: 'https://placehold.co/600x400.png', hint: 'virupaksha temple' },
            { url: 'https://placehold.co/600x400.png', hint: 'tungabhadra river' },
             { url: 'https://placehold.co/600x400.png', hint: 'hampi ruins' },
            { url: 'https://placehold.co/600x400.png', hint: 'ancient architecture' },
            { url: 'https://placehold.co/600x400.png', hint: 'coracle ride' },
        ],
        description: 'Uncover the secrets of the ancient Vijayanagara Empire.',
        inclusions: [],
        exclusions: [],
        itinerary: [],
        batches: [
            { id: 'batch-8-1', startDate: '2024-12-01', endDate: '2024-12-03', availableSlots: 15, maxParticipants: 20, status: 'Pending Approval', notes: 'First batch' },
            { id: 'batch-8-2', startDate: '2024-12-15', endDate: '2024-12-17', availableSlots: 15, maxParticipants: 20, status: 'Pending Approval', priceOverride: 80000 },
        ],
        reviews: [],
        faqs: [],
        organizerId: 'VND003',
        isFeatured: false,
        status: 'Pending Approval',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '9',
        slug: 'andaman-island-paradise',
        title: 'Andaman Island Paradise',
        location: 'Andaman Islands, India',
        city: 'Andaman',
        tripType: 'Relaxation',
        interests: ['Beaches'],
        difficulty: 'Easy',
        duration: '10 Days, 9 Nights',
        minAge: 21,
        maxAge: 55,
        pickupCity: 'Andaman',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Romantic',
        isFeaturedRequest: true,
        price: 280000,
        taxIncluded: false,
        taxPercentage: 12,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'andaman beach ocean',
        gallery: [],
        description: 'A luxurious escape to the crystal-clear waters of the Andaman Islands.',
        inclusions: [],
        exclusions: [],
        itinerary: [],
        batches: [
            { id: 'batch-9-1', startDate: '2025-02-10', endDate: '2025-02-19', availableSlots: 10, maxParticipants: 10, status: 'Rejected', notes: "Organizer documents incomplete" },
        ],
        reviews: [],
        faqs: [],
        organizerId: 'VND004',
        isFeatured: false,
        status: 'Rejected',
        adminNotes: 'Organizer KYC is incomplete. Cannot approve trip.',
        cancellationPolicy: defaultCancellationPolicy,
        cancellationRules: defaultCancellationRules,
    },
    {
        id: '10',
        slug: 'draft-trip-test',
        title: 'Draft Trip Example',
        location: 'TBD',
        city: 'Delhi',
        tripType: 'Adventure',
        interests: [],
        difficulty: 'Easy',
        duration: '1 Day',
        minAge: 18,
        maxAge: 60,
        pickupCity: 'Delhi',
        pickupPoints: [],
        dropoffPoints: [],
        category: 'Adventure',
        isFeaturedRequest: false,
        price: 1000,
        taxIncluded: true,
        taxPercentage: 0,
        image: 'https://placehold.co/600x400.png',
        imageHint: 'placeholder',
        gallery: [],
        description: 'This is a trip in draft status.',
        inclusions: [],
        exclusions: [],
        itinerary: [],
        batches: [],
        reviews: [],
        faqs: [],
        organizerId: 'VND001',
        isFeatured: false,
        status: 'Draft',
        cancellationPolicy: '',
        cancellationRules: [],
    },
];

export const bookings: Booking[] = [
    {
        id: 'BK123',
        tripId: '3',
        userId: 'USR001',
        batchId: 'batch-3-1',
        bookingDate: '2024-07-10',
        status: 'Confirmed',
        refundStatus: 'None',
        subtotal: 440000,
        couponCodeUsed: 'TRAVEL500',
        couponDiscount: 500,
        walletAmountUsed: 2500,
        taxAmount: 0,
        amount: 437000,
        paymentMode: 'Card',
        transactionId: 'txn_1a2b3c4d5e',
        reviewLeft: false,
        travelers: [
            { name: 'Rohan Sharma', email: 'rohan@example.com', phone: '+919876543210' },
            { name: 'Riya Sharma', email: 'riya@example.com', phone: '+919876543211' }
        ]
    },
    {
        id: 'BK124',
        tripId: '2',
        userId: 'USR002',
        batchId: 'batch-2-1',
        bookingDate: '2024-07-12',
        status: 'Confirmed',
        refundStatus: 'None',
        subtotal: 120000,
        couponDiscount: 0,
        walletAmountUsed: 0,
        taxAmount: 6000,
        amount: 126000,
        paymentMode: 'UPI',
        transactionId: 'txn_6f7g8h9i0j',
        reviewLeft: false,
        travelers: [
             { name: 'Priya Patel', email: 'priya@example.com', phone: '+919876543211' }
        ]
    },
    {
        id: 'BK101',
        tripId: '1',
        userId: 'USR001',
        batchId: 'batch-1-1',
        bookingDate: '2023-04-15',
        status: 'Completed',
        refundStatus: 'None',
        subtotal: 96000,
        couponDiscount: 0,
        walletAmountUsed: 0,
        taxAmount: 0,
        amount: 96000, // 1 traveler
        paymentMode: 'Wallet',
        transactionId: 'txn_k1l2m3n4o5',
        reviewLeft: true,
        travelers: [
            { name: 'Rohan Sharma', email: 'rohan@example.com', phone: '+919876543210' }
        ]
    },
    {
        id: 'BK003',
        tripId: '3',
        userId: 'USR004',
        batchId: 'batch-3-1',
        bookingDate: '2024-06-20',
        status: 'Cancelled',
        cancellationReason: 'Change of plans due to a family emergency.',
        refundStatus: 'Pending',
        subtotal: 220000,
        couponDiscount: 0,
        walletAmountUsed: 0,
        taxAmount: 0,
        amount: 220000, // 1 traveler
        paymentMode: 'Card',
        transactionId: 'txn_p6q7r8s9t0',
        reviewLeft: false,
        travelers: [
            { name: 'Ananya Gupta', email: 'ananya@example.com', phone: '+919876543213' }
        ]
    },
    {
        id: 'BK125',
        tripId: '1',
        userId: 'USR004',
        batchId: 'batch-1-2',
        bookingDate: '2024-08-01',
        status: 'Confirmed',
        refundStatus: 'None',
        subtotal: 96000,
        couponDiscount: 0,
        walletAmountUsed: 8000,
        taxAmount: 0,
        amount: 88000,
        paymentMode: 'Wallet',
        transactionId: 'txn_u1v2w3x4y5',
        reviewLeft: false,
        travelers: [
            { name: 'Ananya Gupta', email: 'ananya@example.com', phone: '+919876543213' }
        ]
    },
    {
        id: 'BK126',
        tripId: '5',
        userId: 'USR002',
        batchId: 'batch-5-1', // Note: This batch doesn't exist in mock trips
        bookingDate: '2024-08-05',
        status: 'Completed',
        refundStatus: 'None',
        subtotal: 144000,
        couponDiscount: 0,
        walletAmountUsed: 0,
        taxAmount: 0,
        amount: 144000,
        paymentMode: 'Netbanking',
        transactionId: 'txn_z6a7b8c9d0',
        reviewLeft: false,
        travelers: [
            { name: 'Priya Patel', email: 'priya@example.com', phone: '+919876543211' }
        ]
    },
];

export const disputes: Dispute[] = [
    { id: 'DIS001', bookingId: 'BK003', userId: 'USR004', organizerId: 'VND001', reason: 'Trip was not as described.', status: 'Open', dateReported: '2024-07-01' },
];

export const payouts: Payout[] = [
    {
        id: 'PAY001',
        tripId: '1',
        batchId: 'batch-1-1',
        organizerId: 'VND002',
        totalRevenue: 480000,
        platformCommission: 48000,
        netPayout: 432000,
        status: 'Paid',
        requestDate: '2023-05-15',
        paidDate: '2023-05-16',
        paymentMode: 'NEFT',
        utrNumber: 'N12345678901',
        invoiceUrl: '/invoices/invoice.pdf',
        notes: 'Paid on time.',
    },
    {
        id: 'PAY002',
        tripId: '3',
        batchId: 'batch-3-1',
        organizerId: 'VND001',
        totalRevenue: 1600000,
        platformCommission: 160000,
        netPayout: 1440000,
        status: 'Pending',
        requestDate: '2024-07-18',
        notes: 'Awaiting organizer confirmation.'
    },
    {
        id: 'PAY003',
        tripId: '4',
        batchId: 'batch-4-1',
        organizerId: 'VND003',
        totalRevenue: 248000,
        platformCommission: 24800,
        netPayout: 223200,
        status: 'Pending',
        requestDate: '2024-07-20',
    },
     {
        id: 'PAY004',
        tripId: '6',
        batchId: 'batch-6-1',
        organizerId: 'VND001',
        totalRevenue: 150000,
        platformCommission: 15000,
        netPayout: 135000,
        status: 'Paid',
        requestDate: '2024-08-01',
        paidDate: '2024-08-02',
        paymentMode: 'UPI',
        utrNumber: 'upi-ref-29834u',
        invoiceUrl: '/invoices/invoice.pdf'
    },
];

export const promoCodes: PromoCode[] = [
    { id: 'PROMO001', code: 'TRAVEL500', type: 'Fixed', value: 500, usage: 25, limit: 100, status: 'Active', expiryDate: '2024-12-31' },
    { id: 'PROMO002', code: 'FIRST10', type: 'Percentage', value: 10, usage: 150, limit: 500, status: 'Active', expiryDate: '2025-03-31' },
    { id: 'PROMO003', code: 'MONSOON20', type: 'Percentage', value: 20, usage: 200, limit: 200, status: 'Expired', expiryDate: '2024-08-31' },
    { id: 'PROMO004', code: 'DIWALI1500', type: 'Fixed', value: 1500, usage: 0, limit: 50, status: 'Inactive', expiryDate: '2024-11-15' },
];

export const homeBanners: HomeBanner[] = [
    { id: 'banner1', title: 'Special Monsoon Offers', imageUrl: 'https://placehold.co/1200x400.png', linkUrl: '/search?category=Monsoon', isActive: true },
    { id: 'banner2', title: 'Himalayan Treks Open', imageUrl: 'https://placehold.co/1200x400.png', linkUrl: '/trips/majestic-manali-himalayas', isActive: true },
    { id: 'banner3', title: 'Workations in Goa', imageUrl: 'https://placehold.co/1200x400.png', linkUrl: '/search?category=Workation', isActive: false },
]

export const adminNotifications: AdminNotification[] = [
    { id: 'notif1', type: 'KYC', title: 'KYC Submitted for Himalayan Adventures', description: 'VND001 has submitted documents for verification.', timestamp: '2024-07-20T10:00:00Z', isRead: false, link: '/admin/trip-organisers/VND001', icon: ShieldCheck, iconColor: 'text-blue-500' },
    { id: 'notif2', type: 'Trip', title: 'New Trip Submitted for Approval', description: 'Hampi\'s Ancient Ruins by Bharat Explorers is awaiting approval.', timestamp: '2024-07-21T11:30:00Z', isRead: false, link: '/admin/trips', icon: ListChecks, iconColor: 'text-amber-500' },
    { id: 'notif3', type: 'Payout', title: 'Payout Request from Himalayan Adventures', description: 'Request for ₹1,440,000 has been submitted for trip Rishikesh Adventure Rush.', timestamp: '2024-07-22T09:00:00Z', isRead: true, link: '/admin/payouts', icon: Banknote, iconColor: 'text-green-500' },
    { id: 'notif4', type: 'User', title: 'New User Signup with Referral', description: 'Priya Patel (USR002) signed up using a referral code.', timestamp: '2024-07-22T14:00:00Z', isRead: true, link: '/admin/users', icon: UserRound, iconColor: 'text-indigo-500' },
    { id: 'notif5', type: 'Dispute', title: 'New Dispute Raised', description: 'A new dispute has been opened for booking BK003.', timestamp: '2024-07-23T08:45:00Z', isRead: false, link: '/admin/disputes', icon: AlertTriangle, iconColor: 'text-red-500' },
];

export const auditLogs: AuditLog[] = [
    { id: 'log1', adminId: 'ADM001', adminName: 'Super Admin', action: 'Update', module: 'Settings', details: 'Changed default commission from 10% to 12%', timestamp: '2024-07-22T15:00:00Z' },
    { id: 'log2', adminId: 'ADM002', adminName: 'Finance Manager', action: 'Process', module: 'Payouts', details: 'Processed payout PAY001 for ₹432,000 to Incredible India Tours', timestamp: '2024-07-22T12:30:00Z' },
    { id: 'log3', adminId: 'ADM001', adminName: 'Super Admin', action: 'Approve', module: 'Organisers', details: 'Verified and approved organizer VND002', timestamp: '2024-07-21T18:00:00Z' },
    { id: 'log4', adminId: 'ADM003', adminName: 'Ops Admin', action: 'Reject', module: 'Trips', details: 'Rejected trip "Andaman Island Paradise" (ID: 9)', timestamp: '2024-07-21T14:00:00Z' },
    { id: 'log5', adminId: 'ADM001', adminName: 'Super Admin', action: 'Update', module: 'Users', details: 'Updated profile for user Rohan Sharma (USR001)', timestamp: '2024-07-26T10:00:00Z' },
];

export const adminUsers: AdminUser[] = [
    { id: 'ADM001', name: 'Super Admin', email: 'super@travonex.com', role: 'Super Admin', status: 'Active', lastLogin: '2024-07-26T10:00:00Z' },
    { id: 'ADM002', name: 'Finance Manager', email: 'finance@travonex.com', role: 'Finance Manager', status: 'Active', lastLogin: '2024-07-26T09:30:00Z' },
    { id: 'ADM003', name: 'Support Agent', email: 'support@travonex.com', role: 'Support Agent', status: 'Inactive', lastLogin: '2024-07-25T15:00:00Z' },
    { id: 'ADM004', name: 'Operations Manager', email: 'ops@travonex.com', role: 'Operations Manager', status: 'Active', lastLogin: '2024-07-26T11:00:00Z' }
]
